{
 "title": "Chaos Engineering Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(destination_service_namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(destination_service_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 },
   "content": "<div class=\"dashboard-header text-center\"><span>NAMESPACE: $namespace</span></div>\n\n\n\n"
  },
  {
   "title": "Global Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\", namespace=\"$namespace\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Global Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"destination\", namespace=\"$namespace\", response_code!~\"5.*\"}[1m])) / sum(rate(istio_requests_total{reporter=\"destination\", namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xxs and 5xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 13, "y": 2 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", namespace=\"$namespace\", response_code=~\"[45].*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Service Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"destination\", namespace=\"$namespace\", response_code=\"200\"}[1m])) by (destination_service_name)",
     "legendFormat": "{{destination_service_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"$namespace\"}[1m])) by (le, destination_service_name))",
     "legendFormat": "{{destination_service_name}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"$namespace\"}[1m])) by (le, destination_service_name))",
     "legendFormat": "{{destination_service_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"$namespace\"}[1m])) by (le, destination_service_name))",
     "legendFormat": "{{destination_service_name}}"
    },
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"destination\" , namespace=\"$namespace\", response_code!~\"[45].*\"}[1m])) by (destination_service_name) / sum(rate(istio_requests_total{reporter=\"destination\", namespace=\"$namespace\"}[1m])) by (destination_service_name)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 20, "x": 0, "y": 12 }, "content": "\n\n\n\n" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 14 },
   "content": "<div class=\"dashboard-header text-center\"><span>SERVICE: $service</span></div>\n\n\n\n"
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(1-sum(increase(istio_requests_total{reporter=\"destination\", namespace=\"$namespace\", destination_service_name=\"$service\",response_code!~\"[45].*\"}[1m]))/sum(increase(istio_requests_total{reporter=\"destination\", namespace=\"$namespace\", destination_service_name=\"$service\"}[1m])))"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx and non-4xx responses)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(istio_requests_total{reporter=\"destination\", namespace=\"$namespace\", destination_service_name=\"$service\",response_code!~\"[45].*\"}[1m])) by (destination_service)) / (sum(increase(istio_requests_total{reporter=\"destination\", namespace=\"$namespace\", destination_service_name=\"$service\"}[1m]))by (destination_service))",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 20, "x": 0, "y": 24 }, "content": "\n\n\n\n" },
  {
   "title": "Average",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 26 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{reporter=\"destination\",namespace=\"$namespace\",destination_service_name=\"$service\"}[1m]))/sum(rate(istio_request_duration_milliseconds_count{reporter=\"destination\",namespace=\"$namespace\",destination_service_name=\"$service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Median (P50)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 26 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"$namespace\", destination_service_name=\"$service\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "P90",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 26 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"$namespace\", destination_service_name=\"$service\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "P99",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 26 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"$namespace\", destination_service_name=\"$service\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"$namespace\", destination_service_name=\"$service\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"$namespace\", destination_service_name=\"$service\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"$namespace\", destination_service_name=\"$service\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 20, "x": 0, "y": 38 }, "content": "\n\n\n\n" }
 ]
}