apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-v1
spec:
  selector:
    matchLabels:
      app: bookstore
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
        sidecar.istio.io/inject: 'true'
      labels:
        app: bookstore
        version: v1
    spec:
      containers:
        - name: bookstore
          image: quay.io/kiali/demo_error_rates_server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,8;201,1;202,1"
            - name: SERVER_NAME
              value: "bookstore-v1"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore
  labels:
    app: bookstore
spec:
  ports:
    - name: http
      port: 8888
  selector:
    app: bookstore