---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-v1
spec:
  selector:
    matchLabels:
      app: shop
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: shop
        version: v1
    spec:
      containers:
        - name: shop
          image: quay.io/kiali/demo_error_rates_server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,8;201,1;202,1"
            - name: SERVER_NAME
              value: "shop-v1"
            - name: SERVER_URL
              value: "http://music:8888/status,http://bookstore:8888/status,http://games:8888/status"
---
apiVersion: v1
kind: Service
metadata:
  name: shop
  labels:
    app: shop
spec:
  ports:
    - name: http
      port: 8888
  selector:
    app: shop