apiVersion: apps/v1
kind: Deployment
metadata:
  name: control
  labels:
    app.kubernetes.io/part-of: travel-control
spec:
  selector:
    matchLabels:
      app: control
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
        sidecar.istio.io/inject: 'true'
      labels:
        app: control
        version: v1
    spec:
      containers:
        - name: control
          image: quay.io/kiali/demo_travels_control:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          securityContext:
            privileged: false
          env:
            - name: PORTAL_SERVICES
              value: "voyages.fr;http://voyages-fr:8000,viaggi.it;http://viaggi-it:8000,travels.uk;http://travels-uk:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: control
  labels:
    app: control
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: control