apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: web
        version: v1
    spec:
      containers:
        - name: web
          image: quay.io/kiali/demo_error_rates_client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://shop:8888/status"
            - name: CLIENT_NAME
              value: "web-v1"
            - name: WAIT
              value: "1000"